#generation of Supplementary Figure 6a
options(stringsAsFactors = FALSE)
#please install Seurat v2.3.4. and rDBEC package before use (could be downloaded from this repository)
suppressWarnings(suppressMessages(source("library_source_Seurat.R")))


####################
#please place pathways_X.XX.txt files that were generated by cellchat analysis into working directory

hoge1 = read.table("pathways_0.05.txt", header=T, sep="\t")
rownames(hoge1)=hoge1[,1]
hoge1=hoge1[,2:5]
hoge1[hoge1!="0"]=1
hoge1[hoge1=="0"]=0
hoge1[,1]=as.numeric(hoge1[,1])
hoge1[,2]=as.numeric(hoge1[,2])
hoge1[,3]=as.numeric(hoge1[,3])
hoge1[,4]=as.numeric(hoge1[,4])

hoge2 = hoge1[rowMin(as.matrix(hoge1))==0,]

m2b2g = colorRampPalette(c("grey","magenta"))
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=TRUE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             clustering_distance_rows = "euclidean",
             clustering_method = "ward.D",
             silent=TRUE, main="pct0.05",
             color = m2b2g(1024)
)

hoge2 = hoge2[p$tree_row$order,]
colnames(hoge2)=c("TAS-Seq", "Smart-seq2", "10X v2", "10X v3")
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=FALSE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             silent=TRUE, main="pct0.05",
             color = m2b2g(1024)
)


p = as.ggplot(p[[4]])

ggsave(file = "pct0.05_pathways.png",
       plot =p, device="png",
       units="in", dpi = 300,
       width = 2.6, height = 8.5, limitsize=FALSE)


###############

hoge1 = read.table("pathways_0.15.txt", header=T, sep="\t")
rownames(hoge1)=hoge1[,1]
hoge1=hoge1[,2:5]
hoge1[hoge1!="0"]=1
hoge1[hoge1=="0"]=0
hoge1[,1]=as.numeric(hoge1[,1])
hoge1[,2]=as.numeric(hoge1[,2])
hoge1[,3]=as.numeric(hoge1[,3])
hoge1[,4]=as.numeric(hoge1[,4])

hoge2 = hoge1[rowMin(as.matrix(hoge1))==0,]

m2b2g = colorRampPalette(c("grey","magenta"))
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=TRUE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             clustering_distance_rows = "euclidean",
             clustering_method = "ward.D",
             silent=TRUE, main="pct0.15",
             color = m2b2g(1024)
)

hoge2 = hoge2[p$tree_row$order,]
colnames(hoge2)=c("TAS-Seq", "Smart-seq2", "10X v2", "10X v3")
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=FALSE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             silent=TRUE, main="pct0.15",
             color = m2b2g(1024)
)


p = as.ggplot(p[[4]])

ggsave(file = "pct0.15_pathways.png",
       plot =p, device="png",
       units="in", dpi = 300,
       width = 2.5, height = 8.5, limitsize=FALSE)


###############
hoge1 = read.table("pathways_0.25.txt", header=T, sep="\t")
rownames(hoge1)=hoge1[,1]
hoge1=hoge1[,2:5]
hoge1[hoge1!="0"]=1
hoge1[hoge1=="0"]=0
hoge1[,1]=as.numeric(hoge1[,1])
hoge1[,2]=as.numeric(hoge1[,2])
hoge1[,3]=as.numeric(hoge1[,3])
hoge1[,4]=as.numeric(hoge1[,4])

hoge2 = hoge1[rowMin(as.matrix(hoge1))==0,]

m2b2g = colorRampPalette(c("grey","magenta"))
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=TRUE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             clustering_distance_rows = "euclidean",
             clustering_method = "ward.D",
             silent=TRUE, main="pct0.25",
             color = m2b2g(1024)
)

hoge2 = hoge2[p$tree_row$order,]
colnames(hoge2)=c("TAS-Seq", "Smart-seq2", "10X v2", "10X v3")
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=FALSE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             silent=TRUE, main="pct0.25",
             color = m2b2g(1024)
)

ggsave(file = "pct0.25_pathways.png",
       plot =p, device="png",
       units="in", dpi = 300,
       width = 2.2, height = 10, limitsize=FALSE)


#####################
hoge1 = read.table("pathways_0.5.txt", header=T, sep="\t")
rownames(hoge1)=hoge1[,1]
hoge1=hoge1[,2:5]
hoge1[hoge1!="0"]=1
hoge1[hoge1=="0"]=0
hoge1[,1]=as.numeric(hoge1[,1])
hoge1[,2]=as.numeric(hoge1[,2])
hoge1[,3]=as.numeric(hoge1[,3])
hoge1[,4]=as.numeric(hoge1[,4])

hoge2 = hoge1[rowMin(as.matrix(hoge1))==0,]

m2b2g = colorRampPalette(c("grey","magenta"))
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=TRUE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             clustering_distance_rows = "euclidean",
             clustering_method = "ward.D",
             silent=TRUE, main="pct0.5",
             color = m2b2g(1024)
)

hoge2 = hoge2[p$tree_row$order,]
colnames(hoge2)=c("TAS-Seq", "Smart-seq2", "10X v2", "10X v3")
p = pheatmap(as.data.frame(hoge2),
             scale="none",
             cluster_rows=FALSE,
             cluster_cols=FALSE,
             show_colnames=TRUE,
             show_rownames=TRUE,
             silent=TRUE, main="pct0.5",
             color = m2b2g(1024)
)

ggsave(file = "pct0.5_pathways.png",
       plot =p, device="png",
       units="in", dpi = 300,
       width = 2.2, height = 10, limitsize=FALSE)

